### ISSUE TITLE
esm.sh failing on lit imports

### ISSUE THREAD

**Issue by vospascal** [jspm/jspm#2570]
https://generator.jspm.io/#a2tjYGBiDs0rySzJSU1hyMkscTDWM9QzRrD0U1KT84sSS/KLivWyigFmnjtkMAA

Not 100% sure why this is failing where other providers it works perfectly is this something on the esm.sh side or how the resolving works 
locally I get a similar error.

> node importmap-generator.mjs
```
JspmError: No './directive' exports subpath defined in https://esm.sh/*lit-html@3.1.3/ resolving lit-html/directive imported from https://esm.sh/v135/lit-html@3.1.3/X-ZS8q/esnext/directives/class-map.js.
    at throwExportNotDefined (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:1692:19)
    at Resolver.resolveExport (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:1721:17)
    at async TraceMap.resolve (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2913:59)
    at async TraceMap.visit (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2717:26)
    at async file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2754:13
    at async Promise.all (index 1)
    at async TraceMap.visit (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2749:9)
    at async file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2754:13
    at async Promise.all (index 0)
    at async TraceMap.visit (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2749:9) {
  jspmError: true,
  code: 'MODULE_NOT_FOUND'
}
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

JspmError: No './directive' exports subpath defined in https://esm.sh/*lit-html@3.1.3/ resolving lit-html/directive imported from https://esm.sh/v135/lit-html@3.1.3/X-ZS8q/esnext/directives/class-map.js.
    at throwExportNotDefined (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:1692:19)
    at Resolver.resolveExport (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:1721:17)
    at async TraceMap.resolve (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2913:59)
    at async TraceMap.visit (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2717:26)
    at async file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2754:13
    at async Promise.all (index 1)
    at async TraceMap.visit (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2749:9)
    at async file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2754:13
    at async Promise.all (index 0)
    at async TraceMap.visit (file:///workspaces/widget/node_modules/.pnpm/@jspm+generator@2.0.1/node_modules/@jspm/generator/dist/generator-a8fe28f4.js:2749:9) {
  jspmError: true,
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by pascalvos** [comment]
tried this in local docker looks like it works there 👍 so must be something on wrong else where

**Comment by vospascal** [comment]
tried this in local docker looks like it works there 👍 so there must be something wrong else where

**Comment by guybedford** [comment]
This sounds like an esm.sh issue specifically, could be worth posting there. Thanks for following up though.
